Feature/all pairs
vexchange/info pull request #6
Opened 2021-11-19 00:56 UTC by hochbruj

Draft for selecting V2 pairs instead of tokens -> Not ready to merge! Should be used as input for building new APIs:
- getPairs reads all deployed V2 pairs from chain
- refactored getVolume and getReserves -> currently only working for pairs with WVET token

2021-11-19 17:06 UTC, OliverNChalk commented on pages/index.js
> +      item.tvlInUsd = item.reserves * item.price.base2quote * vetPrice * 2;
Is quote guaranteed to be `VET`?

2021-11-19 17:06 UTC, OliverNChalk commented on utils/api/volume.js
> +  } else return 3;
Return `-1`, it's more C like?

2021-11-19 17:06 UTC, OliverNChalk commented on pages/api/[pool].js
> +  if (vetPosition !== 3) {
So this PR is just a refactor because we do not yet support nonVET pairs?

2021-11-24 01:59 UTC, KennethAshley requested changes
Just a couple comments but nice work on this Jan!

2021-11-24 01:59 UTC, KennethAshley commented on components/TokenTable/index.js
> -            {!ifBelow640 && (
I think we can remove the name and symbol and do something like VEX-VET, SHA-VET, etc. Similar to https://v2.info.uniswap.org/pairs

2021-11-24 01:59 UTC, KennethAshley commented on pages/index.js
> +  console.log("all pairs ", pairs);
we'd want to remove this

2021-11-27 01:32 UTC, xenide approved these changes

2021-11-27 15:28 UTC, OliverNChalk approved these changes

2021-11-30 16:01 UTC, merged